PROJECT_NAME = chaves

RAYLIB_DIR = deps/raylib
INCLUDE_DIR = $(RAYLIB_DIR)/include
LIB_DIR = $(RAYLIB_DIR)/lib

CC = gcc
CFLAGS = -std=c99 -Wall -I$(INCLUDE_DIR)
LDFLAGS = -L$(LIB_DIR) -lraylib \
          -framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo

SRC = $(wildcard *.c)
OBJ = $(SRC:.c=.o)

all: $(PROJECT_NAME)

$(PROJECT_NAME): $(OBJ)
	$(CC) $(OBJ) -o $(PROJECT_NAME) $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f *.o $(PROJECT_NAME)

